### ISSUE TITLE
Rename and move FileNamingStrategy

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#246] opened 2020-11-11 16:01 UTC
The initial idea of the the `FileNamingStrategy` has been to provide an easy-to-use mapping of Entity classes to their corresponding file names to provide a standard naming strategy. As the `FileNamingStrategy` is now used in several places that are not file related (e.g. `InfluxDbSink`) one might consider marking it as deprecated and replace it with a copy of itself but with a proper naming in a proper package e.g. `EntityPersistenceNamingStrategy` or similar. 

Whoever is starting working on this, please DO NOT DELETE the class, but mark it as deprecated and introduce the new class incl. new constructors etc. for the new class incl. an easy converter between old and new naming strategy. For an example of this pls consult me before start working.

**Comment by ahamshubham** [comment] 2021-02-22 17:37
@johanneshiry I have added deprecated tag to the javadoc of the file `FileNamingStrategy.java` and have added a duplicate of the file as `EntityPersistenceNamingStrategy.java` in a separate package `file`. I have also duplicated the test cases for testing `FileNamingStrategy.java`. If everything is okay so far, can you please provide the example for creating a converter between old and new naming strategy?

**Comment by johanneshiry** [comment] 2021-03-05 15:17
Thanks for your work on this. Considering your question, you should create a method e.g. `asEntityPersistenceNamingStrategy():EntityPersistenceNamingStrategy` in `FileNamingStrategy` in order to allow the user to easily convert existing code into new code. (see example code from me, pls pull before moving on with the work)
Additionally, you need to replace all places where `FileNamingStrategy` is used with the new `EntityPersistenceNamingStrategy`.

Pls also consider doing the following:

- adapt javadocs accordingly. There is very often the term `file` used
- pls move `EntityPersistenceNamingStrategy` to package `edu.ie3.datamodel.io.naming` 
- pls do the same refactoring with `HierarchicFileNamingStrategy` (everything except the renaming bc this is still valid)

**Comment by ahamshubham** [comment] 2021-03-05 16:19
Got it. I will work on making these changes.

**Closed** 2021-03-31 07:56 UTC
Labels: good first issue, invalid
