### ISSUE TITLE
Fix bug in GermanVoltageLevelUtils.parse(...)

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/PowerSystemDataModel#118] opened 2020-04-22 13:57 UTC
`CommonVoltageLevel.covers(...)` always throws an exception, even if the correct voltage level could be found. As this method is mainly called by `GermanVoltageLevelUtils.parse(...)` the exception is hidden by the log which is disabled by default in tests. As log level "debug" is disabled in tests, this is not shown in tests but happens there as well. 

To reproduce it just execute `GermanVoltageLevelUtilsTest` and put a breakpoint in `GermanVoltageLevelUtils:122`. Normally, one should **not** end up here for valid data, but one end up here for each element of the test. 

Hence, `CommonVoltageLevel.covers(...)` should be fixed to _not_ throw exceptions for valid data!

**Comment by denstre** [comment] 2020-05-05 19:45
This section:
`    if (idCovered ^ voltageCovered)
      throw new VoltageLevelException(
          "The provided id \""
              + id
              + "\" and rated voltage \""
              + vRated
              + "\" could possibly meet the voltage level \""
              + this.id
              + "\" ("
              + voltageRange
              + "), but are inconsistent.");
    return idCovered; /* voltage covered is always true, otherwise the exception would have been thrown. */`

has been programmed to throw an exception every time idCovered does not equal voltageCovered.
So every time you iterate through the data and do not find a match, this condition is met and the exception is thrown.

Every time you call 
`boolean voltageCovered = covers(vRated);`. -> vRated(0.4)
You get a different result:
Interval [110.0 kV, 220.0 kV) -> false
Interval [20.0 kV, 30.0 kV) -> false
Interval [10.0 kV, 20.0 kV) - > false
Interval [380.0 kV, 560.0 kV) -> false
Interval [0.0 kV, 10.0 kV) -> true

Same for synonymousIds
[Mittelspannung, ms, ms_30kv, mv, mv_30kV] -> false
[Mittelspannung, ms, ms_10kv, mv, mv_10kV] -> false
[Hochspannung, hs, hv] -> false
[Höchstspannung, ehv, ehv_220kv, hoes, hoes_220kv] -> false
[Höchstspannung, ehv, ehv_380kv, hoes, hoes_380kv] -> false
[Niederspannung, lv, ns] -> true

So every time, this result does not match the given vRated Value
`  public static CommonVoltageLevel parse(String id, ComparableQuantity<ElectricPotential> vRated)
      throws VoltageLevelException {
    return germanVoltageLevels.stream()
        .filter(
            voltLvl -> {
              try {
                return voltLvl.covers(id, vRated);`

will call the method again, until both values voltageCovered and idCovered will be true

(hard to explain)

The following PR is the easiest way to solve the problem, but maybe not the best

**Comment by ckittl** [comment] 2020-05-06 06:18
Actually, this was the intended behaviour.

The outcome of the method was supposed to be true only if both `id` _and_ `vRated` are covered by one of the entries. Inside of the `covers` method I am only able to determine, if the input is nicely covered or not _and_ if there might be an inconsistency, but I'm not able to determine, what the best action is.

In the case of parsing it is totally sufficient to log, that something does not match. On another call, I might be reliant on consistent input and the whole thing should fail (I intend to propagate the exception).

What is happening in the case you found to be invalid? Think of calling `GermanVoltageLevelUtils.parse("MV", Quantities.getQuantity(30d, KILOVOLT))`. Then you go through all defined German voltage levels. In most cases false is returned, but for `MV_10KV` ("mv", [10 kV, 20kV)) and `MV_20KV` ("mv", [20 kV, 30kV)) at least the id "mv" matches, but not the rated voltage. The exception is thrown inside of `CommonVoltageLevel#covers`, caught by `GermanVoltageLevelUtils#parse`, logged in debug mode and transferred to alternative result `false`.

Having this in mind, I would suggest to remove or adapt the logging in `GermanVoltageLevelUtils#parse` and keep throwing exceptions in `CommonVoltageLevel#covers`.

**Comment by johanneshiry** [comment] 2020-05-07 10:39
I tried to understand your comment on this but there are a few questions arising when checking the code and reading your comment.

- What does "covered" mean for you in this case? Based on your example I would suspect, that 
`GermanVoltageLevelUtils.parse("MV", Quantities.getQuantity(30d, KILOVOLT))` would be covered from `("mv", [20 kV, 30kV))` as `Quantities.getQuantity(30d, KILOVOLT)` is inside the closed interval `[20 kV, 30kV)` and hence the rated voltage should match and no exception should be thrown. 
- What exactly is "nicely covered" for you? How does it differ from just "covered"?

I just run your test with debug logging on and the following, IMHO at least maximal confusing logging was given:

```java
12:19:30.636 DEBUG - Found some potentially inconsistent voltage level information: The provided id "MS" and rated voltage "15.0 kV" could possibly meet the voltage level "Mittelspannung" (Interval [30.0 kV, 110.0 kV)), but are inconsistent.
12:19:30.638 DEBUG - Found some potentially inconsistent voltage level information: The provided id "MS" and rated voltage "35.0 kV" could possibly meet the voltage level "Mittelspannung" (Interval [20.0 kV, 30.0 kV)), but are inconsistent.
```

Why confusing? 

- both debug logs are returning intervals my provided rated voltage is not even inside. In this case it might be by accident, that they are exactly the opposite (e.g. shown interval in the second line covers rated voltage of first line and vice versa)
- the term "inconsistent" might be confusing as well, as inconsistent might mean something like "it does not make sense what you provided here". But in fact it does(?) as the combination of "MS" and "15.0kV" is not inconsistent, but a valid combination (which is also covered by the intervals, see first bullet point) 
- how do you guess the voltage level? based on which criteria? Because for me it seems not working as expected based on this logging statements

**Comment by johanneshiry** [comment] 2020-05-07 11:12
Dived a little bit more into this which lead me to the following question:
What's the sense of throwing an exception in `CommonVoltageLevel#covers(...)` instead of just returning a boolean indicating if it is covered or not? 

This would have the advantages of 
a) no need to catch the exceptions when the method is called.
b) a clear indication if the common voltage which `covers(...)` method is called covers the provided data or not. atm an exception is thrown only if idCovered != voltageCovered, false is returned only if both are false, true only of both are true.

Furthermore your comment in `ComonVoltageLevel:79` `/* voltage covered is always true, otherwise the exception would have been thrown. */` is invalid (see example below). ´voltageCovered´ can become false (which would let the method to return false). 


**XOR example:**
```java
true ^ true // false
false ^ false // false
true ^ false // true 
false ^ true // true 
```

**Comment by johanneshiry** [comment] 2020-05-07 11:25
Based on what I found so far I would have two solution suggestions:

- remove the exception throwing in `CommonVoltageLevel#covers(...)` and only return true, if `id` and `rated voltage` is covered. Disadvantage of this approach is that the exception message will not be there anymore (I still don't see any benefit of throwing an exception here, because this is a classical true/false indication). 
- keep the exception but adapted the if-clause in CommonVoltageLevel:68 to work as expected that the methods always returns `true` or thrown an exception. Furthermore this needs to be an adapted logging in `GermanVoltageLevelUtils:127` in the sense of that we do not log exceptions but just mark them as false in the filter method as we either return a valid german voltage level or throw an exception that we didn't found one (which IMHO is totally sufficient).

**Comment by ckittl** [comment] 2020-05-07 12:58
After discussion with @johanneshiry:

The outcome of the `CommonVoltageLevel#covers(String, ComparableQuantity)` can be threefold:

1. `id` and `vRated` are covered -> true
2. `id` and `vRated` are not covered -> false
3. Either `id` or `vRated` are covered -> obviously not covered in total, but I can detect, that there might be something wrong with input data.

We decided on, that it is worthwhile to get this additional information (which you don't get, if you simply return false. To examine, what actually is wrong should be done at the place, where the Exception is caught, because only then you know, if it is really of interest, what is wrong or not.

Summarising stuff, @denstre please do the following:

- Reset all changes to master (except of the changes in `Jenkinsfile`, this is a temporary workaround. @johanneshiry will dive deeper into this)
- Only remove the debug logging in `GermanVoltageLevelUtils:127`

Thanks! 😗

**Closed** 2020-05-12 07:56 UTC
Labels: bug
